#ifndef JXS_SERVERNODEDEF_H_
#define JXS_SERVERNODEDEF_H_
//author:hsj

enum ServerNodeType
{
	SERVER_NODE_TYPE_INVALID,
	SERVER_NODE_TYPE_DATA,			//数据服
	SERVER_NODE_TYPE_LOGIN,			//登录服
	SERVER_NODE_TYPE_GAMELOGIC,		//逻辑服
	SERVER_NODE_TYPE_GATEWAY,		//网关服
	SERVER_NODE_TYPE_GLOBAL,		//全局服
	SERVER_NODE_TYPE_CLIENT,		//客户端
	SERVER_NODE_TYPE_GM,			//gm服

	SERVER_NODE_TYPE_COUNT,

};


#endif