#ifndef JXS_BUILDINGDEF_H_
#define JXS_BUILDINGDEF_H_
//author:hsj
//建筑的定义

#include "server_def.h"
#include "game_value_def.h"


//建筑开放条件
enum BuildingOpenCond
{
	BUILDING_OPEN_COND_INVALID,
	BUILDING_OPEN_COND_ROLE_LEVEL,
	BUILDING_OPEN_COND_PALACE_LEVEL,
	BUILDING_OPEN_COND_SERVE_OPEN_DAY,

	BUILDING_OPEN_COND_END,
	BUILDING_OPEN_COND_COUNT = BUILDING_OPEN_COND_END - 1,
};

enum RegionType
{
	REGION_TYPE_INVALID,
	REGION_TYPE_INNER,
	REGION_TYPE_PARTY,
	REGION_TYPE_OUTER,

	REGION_TYPE_END,
	REGION_TYPE_COUNT = REGION_TYPE_END -1,
};

enum BuildingType
{
	BUILDING_TYPE_INVALID,
	BUILDING_TYPE_PALACE,				//皇宫
	BUILDING_TYPE_BARRACKS,				//兵营
	BUILDING_TYPE_ARENA,				//竞技场
	BUILDING_TYPE_SCHEME,				//计略府
	BUILDING_TYPE_CITY_DEFENSE,			//城防所
	BUILDING_TYPE_EQUIPMENT_MANU,		//装备制造所
	BUILDING_TYPE_MINING_WORKSHOP,		//开采工场
	BUILDING_TYPE_WAREHOUSE,			//仓库
	BUILDING_TYPE_TALENTS,				//人才府
	BUILDING_TYPE_MILITARY,				//军事府
	BUILDING_TYPE_CORPS,				//军团
	BUILDING_TYPE_ARSENAL,				//兵器制造所
	BUILDING_TYPE_STRATEGICS,			//兵法研究所
	BUILDING_TYPE_ARMED_ORGANIZATION,	//兵种编制所
	BUILDING_TYPE_TRAINING,				//练兵所
	BUILDING_TYPE_STATION_TROOPS,		//屯所
	BUILDING_TYPE_DRILL_GROUND,			//校场
	BUILDING_TYPE_CORPS_HALL,			//军团大厅
	BUILDING_TYPE_TECH_HALL,			//科技大厅
	BUILDING_TYPE_WELFARE_HOUSE,		//福利院
	BUILDING_TYPE_INFO_STATION,			//情报站
	BUILDING_TYPE_SHOP,					//军团商店
	BUILDING_TYPE_OPERATIONS_CENTER,	//作战中心
	BUILDING_TYPE_TEMPLE,				//宗庙

	BUILDING_TYPE_MARKET = 100,				//市场
	BUILDING_TYPE_FARMLAND,					//农田
	BUILDING_TYPE_LUMBERYARD,				//伐木场
	BUILDING_TYPE_COPPER_ORE,				//铜矿
	BUILDING_TYPE_IRON_ORE,					//铁矿
	BUILDING_TYPE_SILVER_ORE_SPACE = 120,	//银矿空地,特殊空地 
	BUILDING_TYPE_IRON_ORE_SPACE,			//铁矿空地,特殊空地 
	BUILDING_TYPE_NORMAL_ORE = 150,			//普通空地

	BUILDING_TYPE_END,
	BUILDING_TYPE_COUNT = BUILDING_TYPE_END - 1,

};



#endif