#ifndef NOC_COMMON_INCLUDE_SERVERDEF_H_
#define NOC_COMMON_INCLUDE_SERVERDEF_H_

#include "../../include/basic_type_def.h"
#include "../../util/array.h"
#include "../../include/value_def.h"

typedef char AccountName[MAX_64_CHAR_LEN];
typedef char RoleName[MAX_32_CHAR_LEN];
typedef char MsgBuf[MAX_128_CHAR_LEN];
typedef Int64 RoleID;
typedef Int64 ServerNodeID;
typedef std::list<Int32> IdList;
typedef std::vector<Int32> IdArray;
typedef std::set<Int32> IdSet;

//数据库操作标识
enum DBOpt
{
	DB_OPT_INVALID,
	DB_OPT_ADD,
	DB_OPT_UPDATE,
	DB_OPT_DELETE,
};

enum GoldType
{
	RESOURCE_TYPE_GOLD = 6,		//金币
};

enum ResourceType
{
	RESOURCE_TYPE_INVALID,
	
	RESOURCE_TYPE_TAEL,		//银两
	RESOURCE_TYPE_FORAGE,	//粮草
	RESOURCE_TYPE_WOOD,		//木头
	RESOURCE_TYPE_COPPER,	//铜锭
	RESOURCE_TYPE_INGOT,	//铁锭

	RESOURCE_TYPE_END,
	RESOURCE_TYPE_COUNT = RESOURCE_TYPE_END - 1,
};

enum ResourceYieldsType
{
	RESOURCE_YIELDS_INVALID = 18,

	RESOURCE_YIELDS_TAEL,		//银两产量
	RESOURCE_YIELDS_FORAGE,		//粮草产量
	RESOURCE_YIELDS_WOOD,		//木头产量
	RESOURCE_YIELDS_COPPER,		//铜锭产量
	RESOURCE_YIELDS_INGOT,		//铁锭产量

	RESOURCE_YIELDS_END,
	RESOURCE_YIELDS_COUNT = RESOURCE_YIELDS_END - RESOURCE_YIELDS_INVALID - 1,
};


enum ChapterType
{
	FUBEN_TYPE_INVALID,

	FUBEN_TYPE_ROLE_NORMAL,
	FUBEN_TYPE_ROLE_CHALLENGE,

	FUBEN_TYPE_END,
	FUBEN_TYPE_COUNT = FUBEN_TYPE_END - 1,

};

//特殊类属性
enum SpeAttrAdd
{
	SPE_ATTR_ADD_INVALID,
	SPE_ATTR_ADD_BUILDING_SPEED,		//建造加速
	SPE_ATTR_ADD_EXP,					//战斗经验
	SPE_ATTR_ADD_RESOURCE_STORE,		//仓库储存
	SPE_ATTR_ADD_MOVE_SPEED,			//行军速度

	SPE_ATTR_ADD_END,
	SPE_ATTR_ADD_COUNT = SPE_ATTR_ADD_END - 1,
};

//enum AttrAddType
//{
//	ATTR_ADD_INVALID,
//	ATTR_ADD_TECH, // 科技 + 配件 + 道具
//
//	ATTR_ADD_END,
//	ATTR_ADD_COUNT = FUBEN_TYPE_END - 1,
//};

//角色技能类型
enum RoleSkillType
{
	ROLE_SKILL_TYPE_INVALID,
	ROLE_SKILL_HIT,			//命中
	ROLE_SKILL_DODGE,		//闪避
	ROLE_SKILL_BLOW,		//暴击
	ROLE_SKILL_DEBLOW,		//抗暴
	ROLE_SKILL_SHIELD_AP,	//盾兵攻击
	ROLE_SKILL_LANCER_AP,	//枪兵攻击
	ROLE_SKILL_CAVALRY_AP,	//骑兵攻击
	ROLE_SKILL_ARCHER_AP,	//弓兵攻击
	ROLE_SKILL_SHIELD_HP,	//盾兵生命
	ROLE_SKILL_LANCER_HP,	//枪兵生命
	ROLE_SKILL_CAVALRY_HP,	//骑兵生命
	ROLE_SKILL_ARCHER_HP,	//弓兵生命

	ROLE_SKILL_END,
	ROLE_SKILL_COUNT = ROLE_SKILL_END - 1,
};

//角色装备类型
enum RoleEquipType
{
	ROLE_EQUIP_INVALID,
	ROLE_EQUIP_AP,			//攻击
	ROLE_EQUIP_HP,			//生命
	ROLE_EQUIP_HIT,			//命中
	ROLE_EQUIP_DODGE,		//闪避
	ROLE_EQUIP_BLOW,		//暴击
	ROLE_EQUIP_DEBLOW,		//抗暴

	ROLE_EQUIP_END,
	ROLE_EQUIP_COUNT = ROLE_EQUIP_END - 1
};

//武将装备类型
enum GeneralEquipType
{
	GENERAL_EQUIP_BEGIN,
	GENERAL_EQUIP_HAT,			// 头盔
	GENERAL_EQUIP_WEAPON,		// 武器
	GENERAL_EQUIP_BOOK,			// 兵书
	GENERAL_EQUIP_ARMOR,		// 护甲
	GENERAL_EQUIP_YUPEI,		// 玉佩
	GENERAL_EQUIP_GOD_WEAPON,	// 神器
	GENERAL_EQUIP_END,
	GENERAL_EQUIP_COUNT = GENERAL_EQUIP_GOD_WEAPON - GENERAL_EQUIP_HAT + 1,
};


//物品颜色
enum ItemColor
{
	ITEM_COLOR_INVALID,

	ITEM_COLOR_WHITE,		//白色
	ITEM_COLOR_BLUE,		//绿色
	ITEM_COLOR_GREEN,		//蓝色
	ITEM_COLOR_PURPLE,		//紫色
	ITEM_COLOR_ORANGE,		//橙色
	ITEM_COLOR_RED,			//红色

	ITEM_COLOR_END,
	ITEM_COLOR_COUNT = ITEM_COLOR_END - 1,
};

//军团科技类型
enum AllianceTechType
{
	ALLIANCE_TECH_TYPE_INVALID,
	ALLIANCE_TECH_TYPE_HIT,					//命中加成
	ALLIANCE_TECH_TYPE_DODGE,				//闪避加成
	ALLIANCE_TECH_TYPE_BLOW,				//暴击加成
	ALLIANCE_TECH_TYPE_DEBLOW,				//抗暴加成
	ALLIANCE_TECH_TYPE_BASE_HURT_ADD,		//基地伤害
	ALLIANCE_TECH_TYPE_BASE_HURT_SUB,		//基地减伤
	ALLIANCE_TECH_TYPE_CHAPTER_HURT_ADD,	//关卡伤害
	ALLIANCE_TECH_TYPE_CHAPTER_HURT_SUB,	//关卡减伤
	ALLIANCE_TECH_TYPE_GARRISON_SPEED,		//军团驻军移动速度
	ALLIANCE_TECH_TYPE_OVERLOP,				//载重
	ALLIANCE_TECH_TYPE_STORE,				//仓储
	ALLIANCE_TECH_TYPE_BATTLE_EXP,			//战斗经验加成
	ALLIANCE_TECH_TYPE_TAEL,				//银两产出
	ALLIANCE_TECH_TYPE_INGOT,				//铁锭产出
	ALLIANCE_TECH_TYPE_WOOD,				//木头产出
	ALLIANCE_TECH_TYPE_COPPER,				//铜锭产出
	ALLIANCE_TECH_TYPE_FORAGE,				//粮草产出
	ALLIANCE_TECH_TYPE_BOSS_HURT,			//祭坛BOSS伤害		

	ALLIANCE_TECH_TYPE_END,
	ALLIANCE_TECH_TYPE_COUNT = ALLIANCE_TECH_TYPE_END - 1,

};

//军团捐献类型
enum AllianceDonateType
{
	ALLIANCE_DONATE_TYPE_INVALID,
	ALLIANCE_DONATE_TYPE_GOLD,
	ALLIANCE_DONATE_TYPE_TAEL,
	ALLIANCE_DONATE_TYPE_INGOT,
	ALLIANCE_DONATE_TYPE_WOOD,
	ALLIANCE_DONATE_TYPE_COPPER,
	ALLIANCE_DONATE_TYPE_FORAGE,

	ALLIANCE_DONATE_TYPE_END,
	ALLIANCE_DONATE_TYPE_COUNT = ALLIANCE_DONATE_TYPE_END -1,
};

//角色加成属性类型
enum RoleAttrAddType
{
	ROLE_ATTR_ADD_INVALID,
	// BATTLE 
	ROLE_ATTR_ADD_HIT,				//命中
	ROLE_ATTR_ADD_DODGE,			//闪避
	ROLE_ATTR_ADD_BLOW,				//暴击
	ROLE_ATTR_ADD_DEBLOW,			//抗暴
	ROLE_ATTR_ADD_SPUR,				//穿刺
	ROLE_ATTR_ADD_GUARD,			//防护
	ROLE_ATTR_ADD_BLURST,			//爆裂
	ROLE_ATTR_ADD_DEBLURST,			//坚韧
	ROLE_ATTR_ADD_ADD_HURT,			//伤害加成
	ROLE_ATTR_ADD_SUBTRACT_HURT,	//减伤
	ROLE_ATTR_ADD_HP,				//生命
	ROLE_ATTR_ADD_AP,				//攻击
	ROLE_ATTR_ADD_AHEARD,			//先手值
	ROLE_ATTR_ADD_SHIELD_HP,		//盾兵生命
	ROLE_ATTR_ADD_SHIELD_AP,		//盾兵攻击
	ROLE_ATTR_ADD_LANCER_HP,		//枪兵生命
	ROLE_ATTR_ADD_LANCER_AP,		//枪兵攻击
	ROLE_ATTR_ADD_CAVALRY_HP,		//骑兵生命
	ROLE_ATTR_ADD_CAVALRY_AP,		//骑兵攻击
	ROLE_ATTR_ADD_ARCHER_HP,		//弓兵生命
	ROLE_ATTR_ADD_ARCHER_AP,		//弓兵攻击

	// 其它加成
	ROLE_ATTR_ADD_BUILD_SPEED,		//建筑速度加成
	ROLE_ATTR_ADD_EXP_ADD,			//经验加成
	ROLE_ATTR_ADD_MOVE_SPEED_ADD,	//行军速度加成：科技 + 道具
	ROLE_ATTR_ADD_TECH_SPEED_ADD,	//科技研发加成
	ROLE_ATTR_ADD_LEAD_NUM,			//带兵数

	ROLE_ATTR_ADD_END,
	ROLE_ATTR_ADD_COUNT = ROLE_ATTR_ADD_END - 1,
};

//兵法科技格子状态
enum WarTechGridState
{
	WARTECH_GRID_STATE_INVALID = -2,
	WARTECH_GRID_STATE_LOCKED = -1,
	WARTECH_GRID_STATE_UNLOCK = 0,

	//大于0 就是已装备
};

//兵法科技类型
enum WarTechType
{
	WARTECH_TYPE_INVALID,
	WARTECH_TYPE_AP,

	WARTECH_TYPE_END,
	WARTECH_TYPE_COUNT = WARTECH_TYPE_END - 1,
};

//兵法效果类型
enum WarTechEffectType
{
	WARTECH_EFFECT_TYPE_INVALID,
	WARTECH_EFFECT_TYPE_ATTR,			//增加属性
	WARTECH_EFFECT_TYPE_ACTIVE_SOLDIER,	//激活其他兵种科技
	WARTECH_EFFECT_TYPE_ACTIVE_REFORM,	//激活兵种改造
	WARTECH_EFFECT_TYPE_RECRUIT_TIME,	//减少招兵时间

	WARTECH_EFFECT_TYPE_END,
};


//计略俯法术类型
enum SchemeDevelopType
{
	SCHEME_TYPE_INVALID,

	SCHEME_TYPE_FORAGE,				//粮草
	SCHEME_TYPE_SHIELD_HP,			//盾兵生命
	SCHEME_TYPE_SHIELD_AP,			//盾兵攻击
	SCHEME_TYPE_WOOD,				//木头
	SCHEME_TYPE_CAVALRY_HP,			//骑兵生命
	SCHEME_TYPE_CAVALRY_AP,			//骑兵攻击
	SCHEME_TYPE_COPPER,				//铜锭
	SCHEME_TYPE_LANCER_HP,			//枪兵生命
	SCHEME_TYPE_LANCER_AP,			//枪兵攻击
	SCHEME_TYPE_INGOT,				//铁锭
	SCHEME_TYPE_ARCHER_HP,			//弓兵生命
	SCHEME_TYPE_ARCHER_AP,			//弓兵攻击
	SCHEME_TYPE_BUILD_SPEED,		//建造加速
	SCHEME_TYPE_TAEL,				//铸银术
	SCHEME_TYPE_RESOURCE_STORE,		//仓库储存
	SCHEME_TYPE_EXP,				//战斗经验
	SCHEME_TYPE_MOVE_SPEED,			//行军速度

	SCHEME_TYPE_END,
	SCHEME_TYPE_COUNT = SCHEME_TYPE_END - 1,
};

//购买声望类型类型
enum RepuBuyType
{
	REPU_BUY_TYPE_INVALID,

	REPU_BUY_TYPE_RAISE,				//增俸
	REPU_BUY_TYPE_BANQUET,				//宴会,消耗金币
	REPU_BUY_TYPE_PRAISE,				//褒奖,消耗金币
	REPU_BUY_TYPE_TREASURE,				//宝物,消耗金币

	REPU_BUY_TYPE_END,
	REPU_BUY_TYPE_COUNT = REPU_BUY_TYPE_END - 1,
};

// 将领装备属性
enum GeneralEquipAttrType{
	GENERAL_EQUIP_ATTR_INVALID,
	GENERAL_EQUIP_ATTR_WU,
	GENERAL_EQUIP_ATTR_ZHI,
	GENERAL_EQUIP_ATTR_MEI,
	GENERAL_EQUIP_ATTR_LEADERSHIP,
	GENERAL_EQUIP_ATTR_AURA,
	GENERAL_EQUIP_ATTR_STAR,
	GENERAL_EQUIP_ATTR_END,
	GENERAL_EQUIP_ATTR_COUNT = GENERAL_EQUIP_ATTR_END -1,
};

//世界类型
enum WorldType
{
	WORLD_TYPE_INVALID,
	WORLD_TYPE_COMMON,		//普通世界
	WORLD_TYPE_CONDUCT,		//新手世界

	WORLD_TYPE_END,
};


#endif